---
dependencies: []

galaxy_info:
  author: Heather Huggins
  description: Installs and configures Docker on Debian based systems
  company: None
  license: BSD
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - system
